# Generated by Django 3.1 on 2020-09-16 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Nomor Hp menggunakan format: '+999999999'. maksimal nomor hp yaitu 15 karakter.", regex='^\\+?1?\\d{9,15}$')])),
                ('pekerjaan', models.CharField(max_length=50)),
            ],
        ),
    ]
