# Generated by Django 3.1 on 2020-09-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='phone_number',
            new_name='nomor_hp',
        ),
    ]
